QUINUPLETS_RAW = [
    {
        "anchor": "A golden retriever sitting a beach",
        "gamma": "A golden retriver swimming in the ocean",
        "delta": "A tabby cat sitting in a beach",
        "anchor-gamma": "Describe the breed of dog in the image.",
        "anchor-delta": "Describe the setting where the animal is located.",
        "explanation": "The anchor and gamma share the attribute of being retriever dog breeds, while the anchor and delta share the park setting.",
    },
    {
        "anchor": "A red apple on a wooden table",
        "gamma": "A red strawberry in a white bowl",
        "delta": "A green apple on a wooden table",
        "anchor-gamma": "Describe the color of the fruit in the image.",
        "anchor-delta": "Describe the surface on which the fruit is placed.",
        "explanation": "The anchor and gamma share the red color, while the anchor and delta share the wooden table surface.",
    },
    {
        "anchor": "A person wearing a blue raincoat in heavy rain",
        "gamma": "A person wearing a blue sweater on a sunny day",
        "delta": "A person wearing a yellow raincoat in heavy rain",
        "anchor-gamma": "Describe the color of the clothing worn by the person.",
        "anchor-delta": "Describe the weather conditions in the image.",
        "explanation": "The anchor and gamma share the blue clothing color, while the anchor and delta share the rainy weather condition.",
    },
    {
        "anchor": "A steaming cup of coffee next to a laptop",
        "gamma": "A steaming cup of tea on a windowsill",
        "delta": "An iced coffee next to a laptop",
        "anchor-gamma": "Describe the temperature of the beverage in the image.",
        "anchor-delta": "Describe the object next to the coffee.",
        "explanation": "The anchor and gamma share the steaming (hot) attribute of the beverage, while the anchor and delta share the presence of a laptop.",
    },
    {
        "anchor": "A vintage red telephone booth in London",
        "gamma": "A modern red fire hydrant in New York City",
        "delta": "A vintage blue police box in London",
        "anchor-gamma": "Describe the color of the object in the image.",
        "anchor-delta": "Describe the era and location of the object in the image.",
        "explanation": "The anchor and gamma share the red color, while the anchor and delta share the vintage era and London location.",
    },
    {
        "anchor": "A chef cooking pasta in a restaurant kitchen",
        "gamma": "A painter creating a portrait in an art studio",
        "delta": "A waiter serving pasta in a restaurant dining room",
        "anchor-gamma": "Describe the professional activity being performed in the image.",
        "anchor-delta": "Describe the setting related to food service in the image.",
        "explanation": "The anchor and gamma share the attribute of a professional actively working on their craft, while the anchor and delta share the restaurant setting.",
    },
    {
        "anchor": "A lion roaring in the African savanna",
        "gamma": "A wolf howling in a snowy forest",
        "delta": "A giraffe grazing in the African savanna",
        "anchor-gamma": "Describe the vocalization of the animal in the image.",
        "anchor-delta": "Describe the habitat of the animal in the image.",
        "explanation": "The anchor and gamma share the attribute of a loud animal vocalization, while the anchor and delta share the African savanna habitat.",
    },
    {
        "anchor": "A person reading a book on a crowded subway train",
        "gamma": "A person reading a newspaper in an empty library",
        "delta": "A person listening to music on a crowded subway train",
        "anchor-gamma": "Describe the reading activity in the image.",
        "anchor-delta": "Describe the setting and its occupancy in the image.",
        "explanation": "The anchor and gamma share the reading activity, while the anchor and delta share the crowded subway setting.",
    },
    {
        "anchor": "A round birthday cake with lit candles",
        "gamma": "A round pizza with melted cheese",
        "delta": "A square birthday cake with lit candles",
        "anchor-gamma": "Describe the shape of the food item in the image.",
        "anchor-delta": "Describe the type of celebration-related food in the image.",
        "explanation": "The anchor and gamma share the round shape, while the anchor and delta share the birthday cake attribute.",
    },
    {
        "anchor": "A ballerina performing on stage under bright lights",
        "gamma": "A rock guitarist performing on stage under bright lights",
        "delta": "A ballerina practicing in a dance studio with natural light",
        "anchor-gamma": "Describe the performance setting and lighting in the image.",
        "anchor-delta": "Describe the type of dancer in the image.",
        "explanation": "The anchor and gamma share the on-stage performance under bright lights, while the anchor and delta share the ballerina as the subject.",
    },
    {
        "anchor": "A red sports car racing on a Formula 1 track",
        "gamma": "A red speedboat racing on a lake",
        "delta": "A blue sports car racing on a Formula 1 track",
        "anchor-gamma": "Describe the color of the racing vehicle in the image.",
        "anchor-delta": "Describe the type of racing track in the image.",
        "explanation": "The anchor and gamma share the red color of the racing vehicle, while the anchor and delta share the Formula 1 track setting.",
    },
    {
        "anchor": "A person skiing down a snowy mountain slope",
        "gamma": "A person surfing on a large ocean wave",
        "delta": "A person hiking up a snowy mountain trail",
        "anchor-gamma": "Describe the downward motion of the sport in the image.",
        "anchor-delta": "Describe the snowy mountain environment in the image.",
        "explanation": "The anchor and gamma share the downward motion of the sport, while the anchor and delta share the snowy mountain setting.",
    },
    {
        "anchor": "A Victorian-era pocket watch on a velvet cushion",
        "gamma": "A Victorian-era oil lamp on a wooden table",
        "delta": "A modern wristwatch on a velvet cushion",
        "anchor-gamma": "Describe the historical era of the object in the image.",
        "anchor-delta": "Describe the type of timekeeping device and its display surface in the image.",
        "explanation": "The anchor and gamma share the Victorian-era attribute, while the anchor and delta share the watch on a velvet cushion.",
    },
    {
        "anchor": "A vibrant rainbow over a green meadow",
        "gamma": "A vibrant fireworks display over a city skyline",
        "delta": "A faint rainbow over a green meadow",
        "anchor-gamma": "Describe the intensity of the colorful sky phenomenon in the image.",
        "anchor-delta": "Describe the natural sky phenomenon and its setting in the image.",
        "explanation": "The anchor and gamma share the vibrant, colorful sky display, while the anchor and delta share the rainbow over a meadow setting.",
    },
    {
        "anchor": "A wooden sailing ship on a stormy sea",
        "gamma": "A wooden log cabin in a snowy forest",
        "delta": "A modern cruise ship on a stormy sea",
        "anchor-gamma": "Describe the primary material of the main structure in the image.",
        "anchor-delta": "Describe the water conditions and type of vessel in the image.",
        "explanation": "The anchor and gamma share the wooden construction, while the anchor and delta share the stormy sea setting with a ship.",
    },
    {
        "anchor": "A freshly baked chocolate chip cookie on a plate",
        "gamma": "A freshly picked apple on a tree branch",
        "delta": "A stale chocolate chip cookie in a jar",
        "anchor-gamma": "Describe the freshness of the food item in the image.",
        "anchor-delta": "Describe the type of baked good in the image.",
        "explanation": "The anchor and gamma share the freshness attribute, while the anchor and delta share the chocolate chip cookie as the subject.",
    },
    {
        "anchor": "A pair of red high heels on a marble floor",
        "gamma": "A pair of red mittens on a wooden bench",
        "delta": "A pair of black high heels on a marble floor",
        "anchor-gamma": "Describe the color of the clothing accessory in the image.",
        "anchor-delta": "Describe the type of footwear and the surface it's on in the image.",
        "explanation": "The anchor and gamma share the red color, while the anchor and delta share the high heels on a marble floor.",
    },
    {
        "anchor": "A person playing a grand piano in a concert hall",
        "gamma": "A person playing a violin in a street performance",
        "delta": "A person tuning a grand piano in a concert hall",
        "anchor-gamma": "Describe the musical performance activity in the image.",
        "anchor-delta": "Describe the type of piano and its setting in the image.",
        "explanation": "The anchor and gamma share the active musical performance, while the anchor and delta share the grand piano in a concert hall setting.",
    },
    {
        "anchor": "A hot air balloon floating over a desert landscape",
        "gamma": "A hang glider soaring over a mountain range",
        "delta": "A camel walking through a desert landscape",
        "anchor-gamma": "Describe the airborne transportation method in the image.",
        "anchor-delta": "Describe the desert environment in the image.",
        "explanation": "The anchor and gamma share the attribute of airborne transportation, while the anchor and delta share the desert landscape setting.",
    },
    {
        "anchor": "A crackling campfire in a forest clearing at night",
        "gamma": "A crackling fireplace in a cozy living room",
        "delta": "A still, unlit campfire in a forest clearing during the day",
        "anchor-gamma": "Describe the state of the fire in the image.",
        "anchor-delta": "Describe the outdoor fire setting in the image.",
        "explanation": "The anchor and gamma share the crackling fire attribute, while the anchor and delta share the campfire in a forest clearing setting.",
    },
    {
        "anchor": "A ripe banana on a kitchen counter",
        "gamma": "A ripe tomato in a garden",
        "delta": "A green banana on a kitchen counter",
        "anchor-gamma": "Describe the ripeness of the fruit in the image.",
        "anchor-delta": "Describe the type of fruit and its location in the image.",
        "explanation": "The anchor and gamma share the ripeness attribute, while the anchor and delta share the banana on a kitchen counter.",
    },
    {
        "anchor": "A person wearing a graduation cap and gown",
        "gamma": "A person wearing a chef's hat and apron",
        "delta": "A person wearing casual clothes at a graduation ceremony",
        "anchor-gamma": "Describe the professional or ceremonial attire in the image.",
        "anchor-delta": "Describe the context of a graduation in the image.",
        "explanation": "The anchor and gamma share the attribute of specific professional/ceremonial attire, while the anchor and delta share the graduation context.",
    },
    {
        "anchor": "A red double-decker bus in London",
        "gamma": "A red fire truck in New York",
        "delta": "A yellow double-decker bus in London",
        "anchor-gamma": "Describe the color of the large vehicle in the image.",
        "anchor-delta": "Describe the type of public transport and its location in the image.",
        "explanation": "The anchor and gamma share the red color of large vehicles, while the anchor and delta share the double-decker bus in London.",
    },
    {
        "anchor": "A fluffy white cloud in a blue sky",
        "gamma": "A fluffy white cat on a blue couch",
        "delta": "A dark storm cloud in a blue sky",
        "anchor-gamma": "Describe the texture and color of the main subject in the image.",
        "anchor-delta": "Describe the type of cloud and its setting in the image.",
        "explanation": "The anchor and gamma share the fluffy white attribute, while the anchor and delta share the cloud in a blue sky setting.",
    },
    {
        "anchor": "A person surfing on a large wave",
        "gamma": "A person skateboarding in a skate park",
        "delta": "A person sunbathing on a beach with large waves",
        "anchor-gamma": "Describe the board-based sport activity in the image.",
        "anchor-delta": "Describe the beach and wave setting in the image.",
        "explanation": "The anchor and gamma share the board sport activity, while the anchor and delta share the beach with large waves setting.",
    },
    {
        "anchor": "A vintage typewriter on a wooden desk",
        "gamma": "A vintage rotary telephone on a side table",
        "delta": "A modern laptop on a wooden desk",
        "anchor-gamma": "Describe the era of the communication device in the image.",
        "anchor-delta": "Describe the type of work surface and the object on it in the image.",
        "explanation": "The anchor and gamma share the vintage era of communication devices, while the anchor and delta share the wooden desk with a typing device.",
    },
    {
        "anchor": "A blooming cherry blossom tree in a park",
        "gamma": "A blooming sunflower in a field",
        "delta": "A bare cherry blossom tree in winter",
        "anchor-gamma": "Describe the blooming state of the plant in the image.",
        "anchor-delta": "Describe the type of tree in the image.",
        "explanation": "The anchor and gamma share the blooming attribute, while the anchor and delta share the cherry blossom tree as the subject.",
    },
    {
        "anchor": "A person wearing a VR headset in a living room",
        "gamma": "A person wearing noise-cancelling headphones in an office",
        "delta": "A person reading a book in a living room",
        "anchor-gamma": "Describe the tech accessory worn on the head in the image.",
        "anchor-delta": "Describe the room setting in the image.",
        "explanation": "The anchor and gamma share the head-worn tech accessory, while the anchor and delta share the living room setting.",
    },
    {
        "anchor": "A slice of pepperoni pizza on a plate",
        "gamma": "A slice of pepperoni sausage on a cutting board",
        "delta": "A slice of vegetarian pizza on a plate",
        "anchor-gamma": "Describe the presence of pepperoni in the image.",
        "anchor-delta": "Describe the type of food and its presentation in the image.",
        "explanation": "The anchor and gamma share the pepperoni attribute, while the anchor and delta share the pizza slice on a plate.",
    },
    {
        "anchor": "A person doing yoga on a beach at sunset",
        "gamma": "A person meditating in a garden at dawn",
        "delta": "A person jogging on a beach at sunset",
        "anchor-gamma": "Describe the mindfulness activity in the image.",
        "anchor-delta": "Describe the beach setting and time of day in the image.",
        "explanation": "The anchor and gamma share the mindfulness activity, while the anchor and delta share the beach at sunset setting.",
    },
    {
        "anchor": "A classic muscle car at a car show",
        "gamma": "A classic steam locomotive in a train museum",
        "delta": "A modern electric car at a car show",
        "anchor-gamma": "Describe the era of the vehicle in the image.",
        "anchor-delta": "Describe the type of event showcasing vehicles in the image.",
        "explanation": "The anchor and gamma share the classic era of vehicles, while the anchor and delta share the car show setting.",
    },
    {
        "anchor": "A person playing chess in a park",
        "gamma": "A person playing checkers in a living room",
        "delta": "A person jogging in a park",
        "anchor-gamma": "Describe the board game activity in the image.",
        "anchor-delta": "Describe the outdoor recreational setting in the image.",
        "explanation": "The anchor and gamma share the board game activity, while the anchor and delta share the park setting.",
    },
    {
        "anchor": "A panda eating bamboo in a zoo enclosure",
        "gamma": "A koala eating eucalyptus leaves in a tree",
        "delta": "A lion resting in a zoo enclosure",
        "anchor-gamma": "Describe the specialized eating habit of the animal in the image.",
        "anchor-delta": "Describe the zoo setting in the image.",
        "explanation": "The anchor and gamma share the specialized eating habit, while the anchor and delta share the zoo enclosure setting.",
    },
    {
        "anchor": "A person wearing a spacesuit on the moon",
        "gamma": "A person wearing a diving suit underwater",
        "delta": "A person wearing casual clothes on the moon surface set",
        "anchor-gamma": "Describe the specialized environmental suit in the image.",
        "anchor-delta": "Describe the lunar setting in the image.",
        "explanation": "The anchor and gamma share the specialized environmental suit, while the anchor and delta share the moon setting.",
    },
    {
        "anchor": "A colorful hot air balloon in the sky",
        "gamma": "A colorful kite flying in the wind",
        "delta": "A plain white hot air balloon in the sky",
        "anchor-gamma": "Describe the colorful airborne object in the image.",
        "anchor-delta": "Describe the type of large balloon in the sky in the image.",
        "explanation": "The anchor and gamma share the colorful airborne object attribute, while the anchor and delta share the hot air balloon in the sky.",
    },
    {
        "anchor": "A person ice skating on a frozen lake",
        "gamma": "A person roller skating in a park",
        "delta": "A person fishing on a frozen lake",
        "anchor-gamma": "Describe the skating activity in the image.",
        "anchor-delta": "Describe the frozen lake setting in the image.",
        "explanation": "The anchor and gamma share the skating activity, while the anchor and delta share the frozen lake setting.",
    },
    {
        "anchor": "A brown leather briefcase on an office desk",
        "gamma": "A brown leather saddle on a horse",
        "delta": "A black fabric briefcase on an office desk",
        "anchor-gamma": "Describe the material and color of the leather item in the image.",
        "anchor-delta": "Describe the type of bag and its location in the image.",
        "explanation": "The anchor and gamma share the brown leather attribute, while the anchor and delta share the briefcase on an office desk.",
    },
    {
        "anchor": "A person playing a flute in an orchestra",
        "gamma": "A person playing a clarinet in a jazz band",
        "delta": "A person conducting an orchestra",
        "anchor-gamma": "Describe the woodwind instrument being played in the image.",
        "anchor-delta": "Describe the orchestral setting in the image.",
        "explanation": "The anchor and gamma share the woodwind instrument performance, while the anchor and delta share the orchestra setting.",
    },
    {
        "anchor": "A red ladybug on a green leaf",
        "gamma": "A red cardinal bird on a tree branch",
        "delta": "A green caterpillar on a green leaf",
        "anchor-gamma": "Describe the red color of the creature in the image.",
        "anchor-delta": "Describe the type of insect and its location in the image.",
        "explanation": "The anchor and gamma share the red color of the creature, while the anchor and delta share the insect on a green leaf.",
    },
    {
        "anchor": "A person painting a landscape outdoors",
        "gamma": "A person sculpting a statue in a studio",
        "delta": "A person taking a photo of a landscape outdoors",
        "anchor-gamma": "Describe the artistic creation activity in the image.",
        "anchor-delta": "Describe the outdoor setting for capturing the landscape in the image.",
        "explanation": "The anchor and gamma share the artistic creation activity, while the anchor and delta share the outdoor landscape setting.",
    },
    {
        "anchor": "A steaming bowl of ramen noodles",
        "gamma": "A steaming cup of hot chocolate",
        "delta": "A cold bowl of ramen noodles",
        "anchor-gamma": "Describe the steam coming from the food or drink in the image.",
        "anchor-delta": "Describe the type of noodle dish in the image.",
        "explanation": "The anchor and gamma share the steaming attribute, while the anchor and delta share the ramen noodles as the subject.",
    },
    {
        "anchor": "A person riding a horse on a beach",
        "gamma": "A person riding a bicycle on a mountain trail",
        "delta": "A person walking a dog on a beach",
        "anchor-gamma": "Describe the riding activity in the image.",
        "anchor-delta": "Describe the beach setting in the image.",
        "explanation": "The anchor and gamma share the riding activity, while the anchor and delta share the beach setting.",
    },
    {
        "anchor": "A traditional Japanese tea ceremony",
        "gamma": "A traditional English afternoon tea",
        "delta": "A modern coffee shop in Japan",
        "anchor-gamma": "Describe the traditional tea-related cultural activity in the image.",
        "anchor-delta": "Describe the Japanese setting in the image.",
        "explanation": "The anchor and gamma share the traditional tea ceremony attribute, while the anchor and delta share the Japanese setting.",
    },
    {
        "anchor": "A person wearing a bright yellow raincoat in the rain",
        "gamma": "A person wearing a bright yellow safety vest at a construction site",
        "delta": "A person wearing a dark blue raincoat in the rain",
        "anchor-gamma": "Describe the bright yellow safety gear worn in the image.",
        "anchor-delta": "Describe the rainy weather and protective clothing in the image.",
        "explanation": "The anchor and gamma share the bright yellow safety wear, while the anchor and delta share the raincoat in rainy weather.",
    },
    {
        "anchor": "A street performer juggling balls",
        "gamma": "A circus clown juggling pins",
        "delta": "A street performer playing a guitar",
        "anchor-gamma": "Describe the juggling performance in the image.",
        "anchor-delta": "Describe the street performance setting in the image.",
        "explanation": "The anchor and gamma share the juggling performance, while the anchor and delta share the street performer setting.",
    },
    {
        "anchor": "A person scuba diving among coral reefs",
        "gamma": "A person spelunking in an underwater cave",
        "delta": "A person snorkeling above coral reefs",
        "anchor-gamma": "Describe the underwater exploration with breathing equipment in the image.",
        "anchor-delta": "Describe the coral reef setting in the image.",
        "explanation": "The anchor and gamma share the underwater exploration with breathing equipment, while the anchor and delta share the coral reef setting.",
    },
    {
        "anchor": "A ancient Roman statue in a museum",
        "gamma": "A ancient Egyptian sarcophagus in a museum",
        "delta": "A modern art sculpture in a museum",
        "anchor-gamma": "Describe the ancient artifact on display in the image.",
        "anchor-delta": "Describe the museum setting in the image.",
        "explanation": "The anchor and gamma share the ancient artifact attribute, while the anchor and delta share the museum display setting.",
    },
    {
        "anchor": "A person doing a handstand on a yoga mat",
        "gamma": "A person doing a handstand on a balance beam",
        "delta": "A person doing a seated meditation on a yoga mat",
        "anchor-gamma": "Describe the inverted body position in the image.",
        "anchor-delta": "Describe the yoga-related activity and equipment in the image.",
        "explanation": "The anchor and gamma share the handstand position, while the anchor and delta share the yoga mat setting.",
    },
    {
        "anchor": "A vintage Polaroid camera on a shelf",
        "gamma": "A vintage record player on a table",
        "delta": "A modern digital camera on a shelf",
        "anchor-gamma": "Describe the vintage technology item in the image.",
        "anchor-delta": "Describe the type of camera and its location in the image.",
        "explanation": "The anchor and gamma share the vintage technology attribute, while the anchor and delta share the camera on a shelf.",
    },
    {
        "anchor": "A person parasailing over a tropical beach",
        "gamma": "A person paragliding over a mountain range",
        "delta": "A person sunbathing on a tropical beach",
        "anchor-gamma": "Describe the airborne activity using a parachute-like device in the image.",
        "anchor-delta": "Describe the tropical beach setting in the image.",
        "explanation": "The anchor and gamma share the airborne activity with a parachute-like device, while the anchor and delta share the tropical beach setting.",
    },
    {
        "anchor": "A golden retriever puppy playing with a tennis ball",
        "gamma": "A tabby kitten playing with a ball of yarn",
        "delta": "A golden retriever puppy sleeping in a dog bed",
        "anchor-gamma": "Describe the playful behavior of the young animal in the image.",
        "anchor-delta": "Describe the breed and age of the dog in the image.",
        "explanation": "The anchor and gamma share the playful young animal attribute, while the anchor and delta share the golden retriever puppy as the subject.",
    },
    {
        "anchor": "A person skiing down a snowy slope at night",
        "gamma": "A person riding a motorcycle on a dark highway",
        "delta": "A person building a snowman on a snowy slope during the day",
        "anchor-gamma": "Describe the high-speed activity in low-light conditions in the image.",
        "anchor-delta": "Describe the snowy slope setting in the image.",
        "explanation": "The anchor and gamma share the high-speed activity in darkness, while the anchor and delta share the snowy slope setting.",
    },
    {
        "anchor": "A red rose in a crystal vase",
        "gamma": "A red tulip in a garden",
        "delta": "A white rose in a crystal vase",
        "anchor-gamma": "Describe the color of the flower in the image.",
        "anchor-delta": "Describe the type of flower and its container in the image.",
        "explanation": "The anchor and gamma share the red flower color, while the anchor and delta share the rose in a crystal vase.",
    },
    {
        "anchor": "A person playing a grand piano on a stage",
        "gamma": "A person playing a pipe organ in a church",
        "delta": "A person singing on a stage",
        "anchor-gamma": "Describe the keyboard instrument being played in the image.",
        "anchor-delta": "Describe the performance setting in the image.",
        "explanation": "The anchor and gamma share the keyboard instrument performance, while the anchor and delta share the stage performance setting.",
    },
    {
        "anchor": "A freshly baked loaf of bread on a wooden cutting board",
        "gamma": "A freshly picked bunch of grapes on a vine",
        "delta": "A stale loaf of bread on a wooden cutting board",
        "anchor-gamma": "Describe the freshness of the food item in the image.",
        "anchor-delta": "Describe the type of bread and its placement in the image.",
        "explanation": "The anchor and gamma share the freshness attribute, while the anchor and delta share the bread on a wooden cutting board.",
    },
    {
        "anchor": "A person wearing a spacesuit floating in zero gravity",
        "gamma": "A person wearing scuba gear floating underwater",
        "delta": "A person wearing regular clothes standing in a space museum",
        "anchor-gamma": "Describe the specialized suit and floating state in the image.",
        "anchor-delta": "Describe the space-related context in the image.",
        "explanation": "The anchor and gamma share the specialized suit and floating attribute, while the anchor and delta share the space-related context.",
    },
    {
        "anchor": "A colorful hot air balloon festival",
        "gamma": "A vibrant carnival with rides and attractions",
        "delta": "A competitive hot air balloon race",
        "anchor-gamma": "Describe the festive, colorful event in the image.",
        "anchor-delta": "Describe the activity involving hot air balloons in the image.",
        "explanation": "The anchor and gamma share the festive, colorful event attribute, while the anchor and delta share the hot air balloon activity.",
    },
    {
        "anchor": "A person doing yoga on a beach at sunrise",
        "gamma": "A person meditating in a forest at dawn",
        "delta": "A person jogging on a beach at sunrise",
        "anchor-gamma": "Describe the mindfulness activity in the early morning setting in the image.",
        "anchor-delta": "Describe the beach setting at sunrise in the image.",
        "explanation": "The anchor and gamma share the mindfulness activity at dawn/sunrise, while the anchor and delta share the beach at sunrise setting.",
    },
    {
        "anchor": "A vintage typewriter with a sheet of paper",
        "gamma": "A vintage sewing machine with a piece of fabric",
        "delta": "A modern laptop with a blank screen",
        "anchor-gamma": "Describe the vintage mechanical device in the image.",
        "anchor-delta": "Describe the type of writing/typing device in the image.",
        "explanation": "The anchor and gamma share the vintage mechanical device attribute, while the anchor and delta share the writing/typing device aspect.",
    },
    {
        "anchor": "A person paragliding over a mountain range",
        "gamma": "A person hang gliding over a coastline",
        "delta": "A person hiking in a mountain range",
        "anchor-gamma": "Describe the airborne gliding activity in the image.",
        "anchor-delta": "Describe the mountainous setting in the image.",
        "explanation": "The anchor and gamma share the airborne gliding activity, while the anchor and delta share the mountain range setting.",
    },
    {
        "anchor": "A classic red Ferrari on a racetrack",
        "gamma": "A classic red fire truck in a parade",
        "delta": "A modern blue Ferrari on a racetrack",
        "anchor-gamma": "Describe the classic red vehicle in the image.",
        "anchor-delta": "Describe the type of sports car and its location in the image.",
        "explanation": "The anchor and gamma share the classic red vehicle attribute, while the anchor and delta share the Ferrari on a racetrack.",
    },
    {
        "anchor": "A person surfing on a large wave at sunset",
        "gamma": "A person windsurfing on a lake at sunset",
        "delta": "A person building a sandcastle on a beach at sunset",
        "anchor-gamma": "Describe the water sport activity at sunset in the image.",
        "anchor-delta": "Describe the beach setting at sunset in the image.",
        "explanation": "The anchor and gamma share the water sport at sunset, while the anchor and delta share the beach at sunset setting.",
    },
    {
        "anchor": "A steaming cup of coffee with latte art",
        "gamma": "A steaming bowl of soup with a decorative garnish",
        "delta": "An iced coffee with a plain surface",
        "anchor-gamma": "Describe the steam and artistic presentation of the food/drink in the image.",
        "anchor-delta": "Describe the type of coffee beverage in the image.",
        "explanation": "The anchor and gamma share the steaming and artistic presentation, while the anchor and delta share the coffee beverage type.",
    },
    {
        "anchor": "A person wearing a VR headset playing a game",
        "gamma": "A person wearing 3D glasses watching a movie",
        "delta": "A person using a regular computer to play a game",
        "anchor-gamma": "Describe the immersive visual technology being used in the image.",
        "anchor-delta": "Describe the gaming activity in the image.",
        "explanation": "The anchor and gamma share the immersive visual technology, while the anchor and delta share the gaming activity.",
    },
    {
        "anchor": "A bald eagle perched on a tree branch",
        "gamma": "A lion perched on a rock in the savanna",
        "delta": "A robin building a nest on a tree branch",
        "anchor-gamma": "Describe the majestic predator animal in the image.",
        "anchor-delta": "Describe the bird and its position in the tree in the image.",
        "explanation": "The anchor and gamma share the majestic predator attribute, while the anchor and delta share the bird on a tree branch aspect.",
    },
    {
        "anchor": "A person playing a violin in an orchestra",
        "gamma": "A person playing a guitar in a rock band",
        "delta": "A person conducting an orchestra",
        "anchor-gamma": "Describe the string instrument being played in the image.",
        "anchor-delta": "Describe the orchestral setting in the image.",
        "explanation": "The anchor and gamma share the string instrument performance, while the anchor and delta share the orchestra setting.",
    },
    {
        "anchor": "A vibrant rainbow over a waterfall",
        "gamma": "A vibrant aurora borealis in the night sky",
        "delta": "A plain view of a waterfall without a rainbow",
        "anchor-gamma": "Describe the colorful natural sky phenomenon in the image.",
        "anchor-delta": "Describe the waterfall setting in the image.",
        "explanation": "The anchor and gamma share the vibrant sky phenomenon, while the anchor and delta share the waterfall setting.",
    },
    {
        "anchor": "A person doing a backflip on a trampoline",
        "gamma": "A person doing a backflip off a diving board",
        "delta": "A person jumping straight up on a trampoline",
        "anchor-gamma": "Describe the backflip acrobatic move in the image.",
        "anchor-delta": "Describe the trampoline-based activity in the image.",
        "explanation": "The anchor and gamma share the backflip acrobatic move, while the anchor and delta share the trampoline-based activity.",
    },
    {
        "anchor": "A vintage Volkswagen Beetle on a city street",
        "gamma": "A vintage rotary telephone on an office desk",
        "delta": "A modern electric car on a city street",
        "anchor-gamma": "Describe the vintage technology item in the image.",
        "anchor-delta": "Describe the type of vehicle and its urban location in the image.",
        "explanation": "The anchor and gamma share the vintage technology attribute, while the anchor and delta share the car on a city street aspect.",
    },
    {
        "anchor": "A person meditating in a serene Japanese garden",
        "gamma": "A person doing tai chi in a misty mountain valley",
        "delta": "A person jogging through a Japanese garden",
        "anchor-gamma": "Describe the calm, meditative activity in a natural setting in the image.",
        "anchor-delta": "Describe the Japanese garden setting in the image.",
        "explanation": "The anchor and gamma share the calm, meditative activity in nature, while the anchor and delta share the Japanese garden setting.",
    },
    {
        "anchor": "A traditional wooden sailing ship on the ocean",
        "gamma": "A traditional wooden carousel in an amusement park",
        "delta": "A modern cruise ship on the ocean",
        "anchor-gamma": "Describe the traditional wooden structure in the image.",
        "anchor-delta": "Describe the type of ship and its location in the image.",
        "explanation": "The anchor and gamma share the traditional wooden structure attribute, while the anchor and delta share the ship on the ocean aspect.",
    },
    {
        "anchor": "A person ice skating on a frozen lake",
        "gamma": "A person water skiing on a lake",
        "delta": "A person having a picnic beside a frozen lake",
        "anchor-gamma": "Describe the recreational activity on a lake in the image.",
        "anchor-delta": "Describe the frozen lake setting in the image.",
        "explanation": "The anchor and gamma share the recreational lake activity, while the anchor and delta share the frozen lake setting.",
    },
    {
        "anchor": "A chef preparing sushi in a restaurant kitchen",
        "gamma": "A chef decorating a wedding cake in a bakery",
        "delta": "A waiter serving sushi in a restaurant dining room",
        "anchor-gamma": "Describe the chef's food preparation activity in the image.",
        "anchor-delta": "Describe the sushi-related scene in the image.",
        "explanation": "The anchor and gamma share the chef's food preparation activity, while the anchor and delta share the sushi-related aspect.",
    },
    {
        "anchor": "A person riding a camel in the Sahara Desert",
        "gamma": "A person riding an elephant in an Indian jungle",
        "delta": "A person walking on foot in the Sahara Desert",
        "anchor-gamma": "Describe the activity of riding a large animal in the image.",
        "anchor-delta": "Describe the Sahara Desert setting in the image.",
        "explanation": "The anchor and gamma share the large animal riding activity, while the anchor and delta share the Sahara Desert setting.",
    },
    {
        "anchor": "A colorful clownfish swimming in a coral reef",
        "gamma": "A colorful parrot perched in a rainforest tree",
        "delta": "A grey shark swimming near a coral reef",
        "anchor-gamma": "Describe the vibrantly colored animal in its natural habitat in the image.",
        "anchor-delta": "Describe the marine environment in the image.",
        "explanation": "The anchor and gamma share the vibrantly colored animal in its habitat, while the anchor and delta share the coral reef marine setting.",
    },
    {
        "anchor": "A person practicing archery in a forest clearing",
        "gamma": "A person practicing fencing in a gym",
        "delta": "A person hiking in a forest clearing",
        "anchor-gamma": "Describe the precision sport activity in the image.",
        "anchor-delta": "Describe the forest clearing setting in the image.",
        "explanation": "The anchor and gamma share the precision sport activity, while the anchor and delta share the forest clearing setting.",
    },
    {
        "anchor": "A street performer playing a accordion",
        "gamma": "A symphony musician playing a cello",
        "delta": "A street performer juggling balls",
        "anchor-gamma": "Describe the musical instrument being played in the image.",
        "anchor-delta": "Describe the street performance setting in the image.",
        "explanation": "The anchor and gamma share the musical instrument performance, while the anchor and delta share the street performance setting.",
    },
    {
        "anchor": "A person bungee jumping from a tall bridge",
        "gamma": "A person skydiving from an airplane",
        "delta": "A person walking across a tall bridge",
        "anchor-gamma": "Describe the extreme falling sport in the image.",
        "anchor-delta": "Describe the tall bridge setting in the image.",
        "explanation": "The anchor and gamma share the extreme falling sport attribute, while the anchor and delta share the tall bridge setting.",
    },
    {
        "anchor": "A traditional Japanese tea ceremony",
        "gamma": "A traditional Native American peace pipe ceremony",
        "delta": "A modern coffee tasting event in Japan",
        "anchor-gamma": "Describe the traditional cultural ceremony involving a drink or pipe in the image.",
        "anchor-delta": "Describe the Japanese cultural context in the image.",
        "explanation": "The anchor and gamma share the traditional cultural ceremony, while the anchor and delta share the Japanese cultural context.",
    },
    {
        "anchor": "A person solving a Rubik's cube",
        "gamma": "A person solving a crossword puzzle",
        "delta": "A person stacking Rubik's cubes without solving them",
        "anchor-gamma": "Describe the puzzle-solving activity in the image.",
        "anchor-delta": "Describe the presence of Rubik's cubes in the image.",
        "explanation": "The anchor and gamma share the puzzle-solving activity, while the anchor and delta share the presence of Rubik's cubes.",
    },
    {
        "anchor": "A person wearing a spacesuit on Mars",
        "gamma": "A person wearing a hazmat suit in a laboratory",
        "delta": "A person wearing regular clothes looking at a Mars rover model",
        "anchor-gamma": "Describe the specialized protective suit worn in a challenging environment in the image.",
        "anchor-delta": "Describe the Mars-related context in the image.",
        "explanation": "The anchor and gamma share the specialized protective suit in a challenging environment, while the anchor and delta share the Mars-related context.",
    },
    {
        "anchor": "A person painting graffiti on a city wall",
        "gamma": "A person carving a sculpture from a block of marble",
        "delta": "A person cleaning graffiti off a city wall",
        "anchor-gamma": "Describe the artistic creation activity in the image.",
        "anchor-delta": "Describe the urban wall and graffiti context in the image.",
        "explanation": "The anchor and gamma share the artistic creation activity, while the anchor and delta share the urban wall and graffiti context.",
    },
    {
        "anchor": "A honeybee pollinating a sunflower",
        "gamma": "A hummingbird feeding from a trumpet flower",
        "delta": "A ladybug resting on a sunflower petal",
        "anchor-gamma": "Describe the pollination or feeding activity in the image.",
        "anchor-delta": "Describe the sunflower setting in the image.",
        "explanation": "The anchor and gamma share the pollination/feeding activity, while the anchor and delta share the sunflower setting.",
    },
    {
        "anchor": "A person practicing yoga on a mountaintop at sunrise",
        "gamma": "A person practicing tai chi in a garden at dawn",
        "delta": "A person taking photos on a mountaintop at sunrise",
        "anchor-gamma": "Describe the meditative physical activity in an early morning setting in the image.",
        "anchor-delta": "Describe the mountaintop sunrise setting in the image.",
        "explanation": "The anchor and gamma share the meditative physical activity at dawn/sunrise, while the anchor and delta share the mountaintop sunrise setting.",
    },
    {
        "anchor": "A classic red London double-decker bus",
        "gamma": "A classic red British telephone booth",
        "delta": "A modern hybrid London bus in green color",
        "anchor-gamma": "Describe the classic red British icon in the image.",
        "anchor-delta": "Describe the type of London public transport in the image.",
        "explanation": "The anchor and gamma share the classic red British icon attribute, while the anchor and delta share the London bus aspect.",
    },
    {
        "anchor": "A person scuba diving among colorful coral reefs",
        "gamma": "A person snorkeling in a vibrant kelp forest",
        "delta": "A person swimming on the surface above coral reefs",
        "anchor-gamma": "Describe the underwater exploration activity in the image.",
        "anchor-delta": "Describe the coral reef setting in the image.",
        "explanation": "The anchor and gamma share the underwater exploration activity, while the anchor and delta share the coral reef setting.",
    },
    {
        "anchor": "A chef flambing a dish in a restaurant kitchen",
        "gamma": "A blacksmith forging a sword in a workshop",
        "delta": "A chef chopping vegetables in a restaurant kitchen",
        "anchor-gamma": "Describe the activity involving controlled fire or intense heat in the image.",
        "anchor-delta": "Describe the restaurant kitchen setting in the image.",
        "explanation": "The anchor and gamma share the controlled fire/intense heat activity, while the anchor and delta share the restaurant kitchen setting.",
    },
    {
        "anchor": "A person sandboarding down a desert dune",
        "gamma": "A person snowboarding down a snowy slope",
        "delta": "A person riding a camel across a desert dune",
        "anchor-gamma": "Describe the board-riding activity down a slope in the image.",
        "anchor-delta": "Describe the desert dune setting in the image.",
        "explanation": "The anchor and gamma share the board-riding down a slope activity, while the anchor and delta share the desert dune setting.",
    },
    {
        "anchor": "A tightrope walker crossing between two skyscrapers",
        "gamma": "A trapeze artist performing in a circus",
        "delta": "A window washer on a platform between two skyscrapers",
        "anchor-gamma": "Describe the high-altitude acrobatic activity in the image.",
        "anchor-delta": "Describe the urban skyscraper setting in the image.",
        "explanation": "The anchor and gamma share the high-altitude acrobatic activity, while the anchor and delta share the urban skyscraper setting.",
    },
    {
        "anchor": "A person playing a didgeridoo in the Australian outback",
        "gamma": "A person playing an alphorn in the Swiss Alps",
        "delta": "A person cooking on a campfire in the Australian outback",
        "anchor-gamma": "Describe the traditional long wind instrument being played in a natural setting in the image.",
        "anchor-delta": "Describe the Australian outback setting in the image.",
        "explanation": "The anchor and gamma share the traditional long wind instrument in nature, while the anchor and delta share the Australian outback setting.",
    },
    {
        "anchor": "A person creating a sand mandala",
        "gamma": "A person arranging a complex flower arrangement (ikebana)",
        "delta": "A person building a sandcastle on a beach",
        "anchor-gamma": "Describe the intricate, temporary artistic creation in the image.",
        "anchor-delta": "Describe the sand-based creative activity in the image.",
        "explanation": "The anchor and gamma share the intricate, temporary artistic creation, while the anchor and delta share the sand-based creative activity.",
    },
    {
        "anchor": "A vampire bat hanging upside down in a cave",
        "gamma": "A sloth hanging upside down from a tree branch",
        "delta": "A colony of bats flying out of a cave",
        "anchor-gamma": "Describe the animal hanging upside down in the image.",
        "anchor-delta": "Describe the bat-related scene in a cave in the image.",
        "explanation": "The anchor and gamma share the upside-down hanging animal, while the anchor and delta share the bat in a cave setting.",
    },
    {
        "anchor": "A person participating in a color run marathon",
        "gamma": "A person celebrating Holi festival in India",
        "delta": "A person running a traditional marathon",
        "anchor-gamma": "Describe the colorful powder-throwing event in the image.",
        "anchor-delta": "Describe the running event in the image.",
        "explanation": "The anchor and gamma share the colorful powder-throwing event, while the anchor and delta share the running event aspect.",
    },
    {
        "anchor": "A geisha performing a tea ceremony in Kyoto",
        "gamma": "A flamenco dancer performing in Seville",
        "delta": "A sumo wrestler training in a Kyoto dojo",
        "anchor-gamma": "Describe the traditional cultural performance in the image.",
        "anchor-delta": "Describe the traditional Japanese setting in Kyoto in the image.",
        "explanation": "The anchor and gamma share the traditional cultural performance, while the anchor and delta share the traditional Japanese Kyoto setting.",
    },
    {
        "anchor": "A person creating a detailed ice sculpture",
        "gamma": "A person carving an intricate jack-o'-lantern",
        "delta": "A person building an igloo with blocks of ice",
        "anchor-gamma": "Describe the detailed carving activity on a temporary medium in the image.",
        "anchor-delta": "Describe the ice-based creation in the image.",
        "explanation": "The anchor and gamma share the detailed carving on a temporary medium, while the anchor and delta share the ice-based creation.",
    },
    {
        "anchor": "A person riding a penny-farthing bicycle",
        "gamma": "A person riding a unicycle in a circus act",
        "delta": "A person riding a modern bicycle on a city street",
        "anchor-gamma": "Describe the unconventional cycling activity in the image.",
        "anchor-delta": "Describe the bicycle-riding activity in the image.",
        "explanation": "The anchor and gamma share the unconventional cycling activity, while the anchor and delta share the bicycle-riding aspect.",
    },
    {
        "anchor": "A person using a quill pen to write on parchment",
        "gamma": "A person using a brush to create Chinese calligraphy",
        "delta": "A person typing on a vintage typewriter",
        "anchor-gamma": "Describe the traditional handwriting activity in the image.",
        "anchor-delta": "Describe the vintage writing tool in the image.",
        "explanation": "The anchor and gamma share the traditional handwriting activity, while the anchor and delta share the vintage writing tool aspect.",
    },
    {
        "anchor": "A person creating a Rangoli design with colored powder",
        "gamma": "A person creating a Tibetan sand mandala",
        "delta": "A person painting a colorful mural on a wall",
        "anchor-gamma": "Describe the creation of a temporary floor art using colored powder in the image.",
        "anchor-delta": "Describe the colorful artistic creation in the image.",
        "explanation": "The anchor and gamma share the temporary floor art with colored powder, while the anchor and delta share the colorful artistic creation.",
    },
    {
        "anchor": "A person hang gliding over a coastal cliff",
        "gamma": "A person wingsuit flying through a mountain range",
        "delta": "A person hiking along a coastal cliff path",
        "anchor-gamma": "Describe the airborne gliding activity in the image.",
        "anchor-delta": "Describe the coastal cliff setting in the image.",
        "explanation": "The anchor and gamma share the airborne gliding activity, while the anchor and delta share the coastal cliff setting.",
    },
    {
        "anchor": "A person playing a theremin in a concert",
        "gamma": "A person playing a glass armonica in a recital",
        "delta": "A person playing a violin in a concert",
        "anchor-gamma": "Describe the unusual musical instrument being played in the image.",
        "anchor-delta": "Describe the musical performance setting in the image.",
        "explanation": "The anchor and gamma share the unusual musical instrument, while the anchor and delta share the concert performance setting.",
    },
    {
        "anchor": "A person performing a fire poi dance on a beach",
        "gamma": "A person twirling illuminated hula hoops at a festival",
        "delta": "A person building a bonfire on a beach",
        "anchor-gamma": "Describe the illuminated object manipulation performance in the image.",
        "anchor-delta": "Describe the fire-related activity on a beach in the image.",
        "explanation": "The anchor and gamma share the illuminated object manipulation performance, while the anchor and delta share the fire-related beach activity.",
    },
    {
        "anchor": "A person operating an antique printing press",
        "gamma": "A person weaving on a traditional loom",
        "delta": "A person using a modern digital printer",
        "anchor-gamma": "Describe the traditional crafting or manufacturing process in the image.",
        "anchor-delta": "Describe the printing-related activity in the image.",
        "explanation": "The anchor and gamma share the traditional crafting/manufacturing process, while the anchor and delta share the printing-related activity.",
    },
    {
        "anchor": "A person solving a Rubik's Cube blindfolded",
        "gamma": "A person performing a magic card trick",
        "delta": "A person solving a jigsaw puzzle",
        "anchor-gamma": "Describe the impressive mental skill demonstration in the image.",
        "anchor-delta": "Describe the puzzle-solving activity in the image.",
        "explanation": "The anchor and gamma share the impressive mental skill demonstration, while the anchor and delta share the puzzle-solving activity.",
    },
    {
        "anchor": "A person walking on stilts in a parade",
        "gamma": "A person riding a unicycle in a circus",
        "delta": "A person marching in a parade",
        "anchor-gamma": "Describe the unusual mode of movement in a performance setting in the image.",
        "anchor-delta": "Describe the parade participation in the image.",
        "explanation": "The anchor and gamma share the unusual mode of movement in performance, while the anchor and delta share the parade participation.",
    },
    {
        "anchor": "A person creating a topiary in a formal garden",
        "gamma": "A person creating an ice sculpture for a winter festival",
        "delta": "A person planting flowers in a formal garden",
        "anchor-gamma": "Describe the sculptural art form using a natural medium in the image.",
        "anchor-delta": "Describe the formal garden setting in the image.",
        "explanation": "The anchor and gamma share the sculptural art form using a natural medium, while the anchor and delta share the formal garden setting.",
    },
    {
        "anchor": "A person practicing falconry with a hawk",
        "gamma": "A person handling a venomous snake in a show",
        "delta": "A person birdwatching with binoculars",
        "anchor-gamma": "Describe the controlled interaction with a potentially dangerous animal in the image.",
        "anchor-delta": "Describe the bird-related activity in the image.",
        "explanation": "The anchor and gamma share the controlled interaction with a potentially dangerous animal, while the anchor and delta share the bird-related activity.",
    },
    {
        "anchor": "A person riding a penny-farthing bicycle in a historical reenactment",
        "gamma": "A person driving a Ford Model T in an antique car parade",
        "delta": "A person riding a modern bicycle in a cycling race",
        "anchor-gamma": "Describe the use of a vintage mode of transportation in a public event in the image.",
        "anchor-delta": "Describe the bicycle-related activity in the image.",
        "explanation": "The anchor and gamma share the vintage transportation in a public event, while the anchor and delta share the bicycle-related activity.",
    },
    {
        "anchor": "A person using a spinning wheel to make yarn",
        "gamma": "A person using a pottery wheel to shape clay",
        "delta": "A person using a sewing machine to make clothing",
        "anchor-gamma": "Describe the use of a rotating wheel in a traditional craft in the image.",
        "anchor-delta": "Describe the textile-related activity in the image.",
        "explanation": "The anchor and gamma share the use of a rotating wheel in traditional craft, while the anchor and delta share the textile-related activity.",
    },
    {
        "anchor": "A person performing a traditional tea ceremony in Japan",
        "gamma": "A person conducting a wine tasting session in France",
        "delta": "A person practicing calligraphy in Japan",
        "anchor-gamma": "Describe the ritualized beverage tasting activity in the image.",
        "anchor-delta": "Describe the traditional Japanese cultural activity in the image.",
        "explanation": "The anchor and gamma share the ritualized beverage tasting activity, while the anchor and delta share the traditional Japanese cultural activity.",
    },
    {
        "anchor": "A person doing parkour in an urban environment",
        "gamma": "A person practicing capoeira in a park",
        "delta": "A person jogging in an urban environment",
        "anchor-gamma": "Describe the acrobatic movement discipline in the image.",
        "anchor-delta": "Describe the urban setting for physical activity in the image.",
        "explanation": "The anchor and gamma share the acrobatic movement discipline, while the anchor and delta share the urban setting for physical activity.",
    },
    {
        "anchor": "A person using a abacus for calculations",
        "gamma": "A person using a slide rule for engineering calculations",
        "delta": "A person using a modern calculator",
        "anchor-gamma": "Describe the use of a traditional calculation tool in the image.",
        "anchor-delta": "Describe the manual calculation activity in the image.",
        "explanation": "The anchor and gamma share the use of a traditional calculation tool, while the anchor and delta share the manual calculation activity.",
    },
    {
        "anchor": "A person creating a miniature ship in a bottle",
        "gamma": "A person building an elaborate house of cards",
        "delta": "A person painting a detailed maritime scene",
        "anchor-gamma": "Describe the creation of a delicate, precise miniature structure in the image.",
        "anchor-delta": "Describe the maritime-related creative activity in the image.",
        "explanation": "The anchor and gamma share the creation of a delicate, precise miniature structure, while the anchor and delta share the maritime-related creative activity.",
    },
    {
        "anchor": "A person playing a didgeridoo in the Australian outback",
        "gamma": "A person playing a Native American flute in a canyon",
        "delta": "A person observing wildlife in the Australian outback",
        "anchor-gamma": "Describe the traditional wind instrument being played in a natural setting in the image.",
        "anchor-delta": "Describe the Australian outback setting in the image.",
        "explanation": "The anchor and gamma share the traditional wind instrument in a natural setting, while the anchor and delta share the Australian outback setting.",
    },
    {
        "anchor": "A person creating a detailed sand sculpture on a beach",
        "gamma": "A person carving an intricate ice sculpture",
        "delta": "A person sunbathing on a beach",
        "anchor-gamma": "Describe the creation of a detailed temporary sculpture in the image.",
        "anchor-delta": "Describe the beach setting in the image.",
        "explanation": "The anchor and gamma share the creation of a detailed temporary sculpture, while the anchor and delta share the beach setting.",
    },
    {
        "anchor": "A person performing a traditional Maori haka dance",
        "gamma": "A person performing a traditional Native American rain dance",
        "delta": "A person watching a Maori cultural performance",
        "anchor-gamma": "Describe the traditional cultural dance performance in the image.",
        "anchor-delta": "Describe the Maori cultural context in the image.",
        "explanation": "The anchor and gamma share the traditional cultural dance performance, while the anchor and delta share the Maori cultural context.",
    },
    {
        "anchor": "A person using a quill pen to write on parchment",
        "gamma": "A person using charcoal to draw on cave walls",
        "delta": "A person typing on a vintage typewriter",
        "anchor-gamma": "Describe the use of an ancient writing or drawing tool in the image.",
        "anchor-delta": "Describe the historical writing activity in the image.",
        "explanation": "The anchor and gamma share the use of an ancient writing/drawing tool, while the anchor and delta share the historical writing activity.",
    },
    {
        "anchor": "A person practicing falconry with a trained hawk",
        "gamma": "A person leading a sled dog team in the Arctic",
        "delta": "A person birdwatching with binoculars",
        "anchor-gamma": "Describe the skilled animal handling for a specific purpose in the image.",
        "anchor-delta": "Describe the bird-related activity in the image.",
        "explanation": "The anchor and gamma share the skilled animal handling for a purpose, while the anchor and delta share the bird-related activity.",
    },
    {
        "anchor": "A person creating a Rangoli design with colored powder",
        "gamma": "A person making a chalk drawing on a sidewalk",
        "delta": "A person arranging flowers for a Hindu ceremony",
        "anchor-gamma": "Describe the creation of temporary ground art in the image.",
        "anchor-delta": "Describe the colorful Indian cultural tradition in the image.",
        "explanation": "The anchor and gamma share the creation of temporary ground art, while the anchor and delta share the colorful Indian cultural tradition.",
    },
    {
        "anchor": "A person tightrope walking between two mountain peaks",
        "gamma": "A person performing on a trapeze in a circus",
        "delta": "A person hiking between two mountain peaks",
        "anchor-gamma": "Describe the high-altitude balancing performance in the image.",
        "anchor-delta": "Describe the mountain peak setting in the image.",
        "explanation": "The anchor and gamma share the high-altitude balancing performance, while the anchor and delta share the mountain peak setting.",
    },
    {
        "anchor": "A person creating a bonsai tree",
        "gamma": "A person sculpting a topiary in a formal garden",
        "delta": "A person planting a full-sized tree in a park",
        "anchor-gamma": "Describe the artistic shaping of a living plant in the image.",
        "anchor-delta": "Describe the tree-related activity in the image.",
        "explanation": "The anchor and gamma share the artistic shaping of a living plant, while the anchor and delta share the tree-related activity.",
    },
    {
        "anchor": "A person performing a fire-eating act",
        "gamma": "A person swallowing a sword in a street performance",
        "delta": "A firefighter extinguishing a fire",
        "anchor-gamma": "Describe the dangerous performance art in the image.",
        "anchor-delta": "Describe the fire-related activity in the image.",
        "explanation": "The anchor and gamma share the dangerous performance art, while the anchor and delta share the fire-related activity.",
    },
    {
        "anchor": "A person practicing Tai Chi in a misty bamboo forest",
        "gamma": "A person doing yoga on a beach at sunrise",
        "delta": "A person hiking through a bamboo forest",
        "anchor-gamma": "Describe the meditative physical practice in a natural setting in the image.",
        "anchor-delta": "Describe the bamboo forest setting in the image.",
        "explanation": "The anchor and gamma share the meditative physical practice in nature, while the anchor and delta share the bamboo forest setting.",
    },
    {
        "anchor": "A person operating an old-fashioned weaving loom",
        "gamma": "A person using a traditional pottery wheel",
        "delta": "A person using a modern sewing machine",
        "anchor-gamma": "Describe the use of a traditional craft-making device in the image.",
        "anchor-delta": "Describe the textile-related activity in the image.",
        "explanation": "The anchor and gamma share the use of a traditional craft-making device, while the anchor and delta share the textile-related activity.",
    },
    {
        "anchor": "A person playing a theremin in a concert hall",
        "gamma": "A person playing a glass harmonica in a recital",
        "delta": "A person conducting an orchestra in a concert hall",
        "anchor-gamma": "Describe the unusual musical instrument being played in the image.",
        "anchor-delta": "Describe the formal musical performance setting in the image.",
        "explanation": "The anchor and gamma share the unusual musical instrument, while the anchor and delta share the formal musical performance setting.",
    },
    {
        "anchor": "A person creating a mandala with colored sand",
        "gamma": "A person arranging a complex ikebana flower arrangement",
        "delta": "A person meditating in front of a painted mandala",
        "anchor-gamma": "Describe the creation of a detailed, symbolic artistic arrangement in the image.",
        "anchor-delta": "Describe the mandala-related spiritual context in the image.",
        "explanation": "The anchor and gamma share the creation of a detailed, symbolic artistic arrangement, while the anchor and delta share the mandala-related spiritual context.",
    },
    {
        "anchor": "A person participating in a tomato-throwing festival (La Tomatina)",
        "gamma": "A person engaged in a massive snowball fight",
        "delta": "A person harvesting tomatoes in a field",
        "anchor-gamma": "Describe the playful mass participation event involving throwing objects in the image.",
        "anchor-delta": "Describe the tomato-related activity in the image.",
        "explanation": "The anchor and gamma share the playful mass participation event involving throwing objects, while the anchor and delta share the tomato-related activity.",
    },
    {
        "anchor": "A person performing a traditional Japanese tea ceremony",
        "gamma": "A person conducting a formal wine tasting",
        "delta": "A person practicing Japanese calligraphy",
        "anchor-gamma": "Describe the ritualized beverage appreciation ceremony in the image.",
        "anchor-delta": "Describe the traditional Japanese cultural practice in the image.",
        "explanation": "The anchor and gamma share the ritualized beverage appreciation ceremony, while the anchor and delta share the traditional Japanese cultural practice.",
    },
    {
        "anchor": "A person riding a penny-farthing bicycle in a historical parade",
        "gamma": "A person driving a Model T Ford in an antique car show",
        "delta": "A person riding a modern bicycle in a race",
        "anchor-gamma": "Describe the use of a vintage mode of transportation in a public event in the image.",
        "anchor-delta": "Describe the bicycle-related activity in the image.",
        "explanation": "The anchor and gamma share the use of a vintage mode of transportation in a public event, while the anchor and delta share the bicycle-related activity.",
    },
    {
        "anchor": "A person doing parkour in an urban environment",
        "gamma": "A person free climbing a tall building",
        "delta": "A person jogging through city streets",
        "anchor-gamma": "Describe the extreme urban movement activity in the image.",
        "anchor-delta": "Describe the urban setting for physical activity in the image.",
        "explanation": "The anchor and gamma share the extreme urban movement activity, while the anchor and delta share the urban setting for physical activity.",
    },
    {
        "anchor": "A person creating a detailed miniature ship in a bottle",
        "gamma": "A person building an elaborate house of cards",
        "delta": "A person painting a maritime scene on canvas",
        "anchor-gamma": "Describe the creation of a delicate, miniature structure requiring great precision in the image.",
        "anchor-delta": "Describe the maritime-themed artistic activity in the image.",
        "explanation": "The anchor and gamma share the creation of a delicate, miniature structure requiring precision, while the anchor and delta share the maritime-themed artistic activity.",
    },
    {
        "anchor": "A person competing in a wife-carrying contest",
        "gamma": "A person participating in a cheese-rolling competition",
        "delta": "A person running in a traditional marathon",
        "anchor-gamma": "Describe the unusual competitive event in the image.",
        "anchor-delta": "Describe the running-based competition in the image.",
        "explanation": "The anchor and gamma share the unusual competitive event, while the anchor and delta share the running-based competition.",
    },
    {
        "anchor": "A person creating a human tower in a Catalan festival",
        "gamma": "A group performing an elaborate cheerleading pyramid",
        "delta": "A person watching a Catalan festival from the crowd",
        "anchor-gamma": "Describe the creation of a human structure as a performance in the image.",
        "anchor-delta": "Describe the Catalan festival context in the image.",
        "explanation": "The anchor and gamma share the creation of a human structure as a performance, while the anchor and delta share the Catalan festival context.",
    },
    {
        "anchor": "A person spinning wool on an old-fashioned spinning wheel",
        "gamma": "A person making rope by hand using traditional methods",
        "delta": "A person knitting with modern knitting needles",
        "anchor-gamma": "Describe the traditional fiber-crafting method in the image.",
        "anchor-delta": "Describe the wool-related crafting activity in the image.",
        "explanation": "The anchor and gamma share the traditional fiber-crafting method, while the anchor and delta share the wool-related crafting activity.",
    },
    {
        "anchor": "A person performing a traditional sword swallowing act",
        "gamma": "A person performing an extreme piercing ritual",
        "delta": "A person sharpening a sword for a historical reenactment",
        "anchor-gamma": "Describe the dangerous body modification or risk-taking performance in the image.",
        "anchor-delta": "Describe the sword-related activity in the image.",
        "explanation": "The anchor and gamma share the dangerous body modification or risk-taking performance, while the anchor and delta share the sword-related activity.",
    },
    {
        "anchor": "A person making shadow puppets for a traditional play",
        "gamma": "A person manipulating marionettes in a puppet theater",
        "delta": "A person applying makeup for a traditional theater performance",
        "anchor-gamma": "Describe the puppet-based storytelling performance in the image.",
        "anchor-delta": "Describe the preparation for a traditional theatrical performance in the image.",
        "explanation": "The anchor and gamma share the puppet-based storytelling performance, while the anchor and delta share the preparation for a traditional theatrical performance.",
    },
    {
        "anchor": "A person panning for gold in a river",
        "gamma": "A person searching for buried treasure with a metal detector",
        "delta": "A person fishing in a river",
        "anchor-gamma": "Describe the treasure hunting activity in the image.",
        "anchor-delta": "Describe the river-based recreational activity in the image.",
        "explanation": "The anchor and gamma share the treasure hunting activity, while the anchor and delta share the river-based recreational activity.",
    },
    {
        "anchor": "A person performing a traditional fire walk",
        "gamma": "A person walking on broken glass in a sideshow act",
        "delta": "A person tending a bonfire at a cultural event",
        "anchor-gamma": "Describe the dangerous barefoot walking performance in the image.",
        "anchor-delta": "Describe the fire-related cultural activity in the image.",
        "explanation": "The anchor and gamma share the dangerous barefoot walking performance, while the anchor and delta share the fire-related cultural activity.",
    },
    {
        "anchor": "A person creating a complex domino toppling setup",
        "gamma": "A person building an elaborate Rube Goldberg machine",
        "delta": "A person playing a game of dominoes",
        "anchor-gamma": "Describe the creation of a complex chain reaction setup in the image.",
        "anchor-delta": "Describe the domino-related activity in the image.",
        "explanation": "The anchor and gamma share the creation of a complex chain reaction setup, while the anchor and delta share the domino-related activity.",
    },
    {
        "anchor": "A person practicing extreme ironing on a mountaintop",
        "gamma": "A person doing underwater hockey",
        "delta": "A person hiking to a mountaintop",
        "anchor-gamma": "Describe the unusual extreme sport in the image.",
        "anchor-delta": "Describe the mountaintop-related activity in the image.",
        "explanation": "The anchor and gamma share the unusual extreme sport, while the anchor and delta share the mountaintop-related activity.",
    },
    {
        "anchor": "A person creating a detailed crop circle in a field",
        "gamma": "A person making a large-scale sand drawing on a beach",
        "delta": "A person harvesting crops in a field",
        "anchor-gamma": "Describe the creation of a large-scale ground art in the image.",
        "anchor-delta": "Describe the field-based activity in the image.",
        "explanation": "The anchor and gamma share the creation of large-scale ground art, while the anchor and delta share the field-based activity.",
    },
    {
        "anchor": "A person doing a freefall skydive",
        "gamma": "A person bungee jumping from a tall bridge",
        "delta": "A person preparing a parachute for packing",
        "anchor-gamma": "Describe the extreme falling sport in the image.",
        "anchor-delta": "Describe the skydiving-related activity in the image.",
        "explanation": "The anchor and gamma share the extreme falling sport, while the anchor and delta share the skydiving-related activity.",
    },
    {
        "anchor": "A person creating a balloon animal sculpture",
        "gamma": "A person making an origami figure",
        "delta": "A person releasing helium balloons at an event",
        "anchor-gamma": "Describe the creation of a shaped object from a flat or formless material in the image.",
        "anchor-delta": "Describe the balloon-related activity in the image.",
        "explanation": "The anchor and gamma share the creation of a shaped object from a flat or formless material, while the anchor and delta share the balloon-related activity.",
    },
    {
        "anchor": "A person performing a traditional Japanese tea ceremony",
        "gamma": "A person conducting a formal Turkish coffee reading",
        "delta": "A person practicing Japanese calligraphy",
        "anchor-gamma": "Describe the ritualized beverage preparation and consumption ceremony in the image.",
        "anchor-delta": "Describe the traditional Japanese cultural practice in the image.",
        "explanation": "The anchor and gamma share the ritualized beverage ceremony, while the anchor and delta share the traditional Japanese cultural practice.",
    },
    {
        "anchor": "A person creating a detailed ice sculpture",
        "gamma": "A person carving an intricate pumpkin for Halloween",
        "delta": "A person building an igloo",
        "anchor-gamma": "Describe the temporary artistic carving on a perishable medium in the image.",
        "anchor-delta": "Describe the ice-based creation in the image.",
        "explanation": "The anchor and gamma share the temporary artistic carving on a perishable medium, while the anchor and delta share the ice-based creation.",
    },
    {
        "anchor": "A person walking a tightrope between two skyscrapers",
        "gamma": "A person performing a high-wire act in a circus",
        "delta": "A person washing windows on a skyscraper",
        "anchor-gamma": "Describe the high-altitude balancing performance in the image.",
        "anchor-delta": "Describe the skyscraper-related activity in the image.",
        "explanation": "The anchor and gamma share the high-altitude balancing performance, while the anchor and delta share the skyscraper-related activity.",
    },
    {
        "anchor": "A person creating a sand mandala",
        "gamma": "A person making a Native American medicine wheel",
        "delta": "A person meditating in front of a painted mandala",
        "anchor-gamma": "Describe the creation of a symbolic circular diagram for spiritual purposes in the image.",
        "anchor-delta": "Describe the mandala-related spiritual context in the image.",
        "explanation": "The anchor and gamma share the creation of a symbolic circular diagram for spiritual purposes, while the anchor and delta share the mandala-related spiritual context.",
    },
    {
        "anchor": "A person performing parkour in an urban environment",
        "gamma": "A person doing freestyle skateboarding in a skate park",
        "delta": "A person jogging through city streets",
        "anchor-gamma": "Describe the acrobatic movement sport in a specially designed or adapted environment in the image.",
        "anchor-delta": "Describe the urban physical activity in the image.",
        "explanation": "The anchor and gamma share the acrobatic movement sport in a specially designed or adapted environment, while the anchor and delta share the urban physical activity.",
    },
    {
        "anchor": "A person playing a glass harmonica",
        "gamma": "A person playing a theremin",
        "delta": "A person playing a traditional piano",
        "anchor-gamma": "Describe the unusual or rare musical instrument being played in the image.",
        "anchor-delta": "Describe the musical performance in the image.",
        "explanation": "The anchor and gamma share the unusual or rare musical instrument, while the anchor and delta share the musical performance aspect.",
    },
    {
        "anchor": "A person creating a topiary garden sculpture",
        "gamma": "A person trimming a bonsai tree",
        "delta": "A person planting flowers in a garden",
        "anchor-gamma": "Describe the artistic shaping of living plants in the image.",
        "anchor-delta": "Describe the gardening activity in the image.",
        "explanation": "The anchor and gamma share the artistic shaping of living plants, while the anchor and delta share the gardening activity.",
    },
    {
        "anchor": "A person performing a fire poi dance",
        "gamma": "A person juggling flaming torches",
        "delta": "A person doing a traditional Maori dance",
        "anchor-gamma": "Describe the performance involving skilled manipulation of fire in the image.",
        "anchor-delta": "Describe the Polynesian-originated performance in the image.",
        "explanation": "The anchor and gamma share the performance involving skilled manipulation of fire, while the anchor and delta share the Polynesian-originated performance aspect.",
    },
]

if __name__ == "__main__":
    print(len(QUINUPLETS_RAW))


INSTRUCTS_PROMPT = """
Your mission today is to generate data points composed of 5-element quintuplets:
Prompt anchor: A prompt that describes the anchor image.
Prompt gamma: A prompt that describes the gamma image.
Prompt delta: A prompt that describes the delta image.
Text anchor-gamma: A text related to the commonality between the anchor and gamma image, which is not shared with the delta image.
Text anchor-delta: A text related to the commonality between the anchor and delta image, which is not shared with the gamma image.

Example 1:
Prompt anchor: A full image of a very tall man with blonde hair.
Prompt gamma: A full image of a tall man with gray hair.
Prompt y: A full image of a short man with blonde hair.
Text anchor-gamma: Describe the height of the person in the image.
Text anchor-delta: Describe the hair color of the person in the image.

Example 2:
Prompt anchor: A blue convertible parked near a beach.
Prompt gamma: A red sports car driving on a highway.
Prompt delta: A blue bicycle leaning against a tree in nature.
Text anchor-gamma: Describe the type of vehicle in the image.
Text anchor-delta: Describe the color of the vehicle in the image.

Example 3:
Prompt anchor: An image of a glass of red wine on a picnic blanket in Yosemite park.
Prompt gamma: An image of a glass of red wine on a table in a fancy restaurant.
Prompt y: An image of a hotdog on a picnic blanket in Yosemite park.
Text anchor-gamma: Describe the drink in the image.
Text anchor-delta: Describe the location of the image.
Additional instructions:

The rule: for each prompt in [gamma, delta], ancor-prompt should define a category of which they share a common attribute described in their prompts.
Feel free to be creative and use your imagination to generate the prompts.
Ensure the shared attributes between 'anchor' and 'gamma' are not shared with 'delta', and vice versa.
Each text (anchor-gamma and anchor-delta) must clearly relate to the shared attribute and distinctly separate it from the non-shared image.
Write down a short explanation for each quintuplet.
Output your results in a list of dictionaries with keys 'anchor', 'gamma', 'delta', 'anchor-gamma', 'anchor-delta', 'explanation'.
The commonality between the images should be clear, easy to understand, and not implicit.
Generte 20 quintuplets.
"""
